### ISSUE TITLE
这个工程不更新了么

### ISSUE THREAD

**Issue by wuxiangjinxing** [might-and-magic/mm678-i18n#1]
整合版已经更新过很多回了，这个汉化包没有需要更新的地方吗？

只是确认一下，因为我下百度盘（贴吧链接）很慢，所以如果可以从github下载会方便很多。

谢谢。

**Comment by tomchen** [comment]
贴吧上百度网盘里有21年7月更新的简体中文完整包（非补丁）

还没随12月底和1月初的版本更新，一个月内更新（以确保整合版和新更新的GrayFace补丁稳定下来——这段时间GrayFace和整合版多次更新修正，可能不太稳定）

补丁以后当然也可以更新。但原版整合版的版本和安装方式都挺乱，不同的安装方法都会使得得到的文件有些差异。汉化补丁要应用在哪个版本的原版整合版上，这也是问题

**Comment by tomchen** [comment]
这不，整合版于2月12号果然又更新了。。

接下来再继续等等它会不会再次更新。同时我也会看看翻译要改哪些部分。总之汉化最早会三月初出。。
